version: '3.8'

services:
  nca-toolkit:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: nca-toolkit
    platform: linux/arm64
    environment: 
      - 'API_KEY=${API_KEY}' 
      - 'S3_ENDPOINT_URL=${S3_ENDPOINT_URL}'
      - 'S3_ACCESS_KEY=${S3_ACCESS_KEY}' 
      - 'S3_SECRET_KEY=${S3_SECRET_KEY}' 
      - 'S3_BUCKET_NAME=nca-toolkit' 
      - 'S3_REGION=None'
    expose:
      - '8080'
    networks:
      - nca-network
    restart: unless-stopped

networks:
  nca-network:
    driver: bridge
